### ISSUE TITLE
Is this project no longer mobile phone friendly ?

### ISSUE THREAD

**Issue by KubilayKerim** [bigbluebutton/bigbluebutton-tablet#49]
Name changed first as mobile-tablet and now only tablet I wonder is this now no longer for phones ? If so will there be another project for phones or did you guys unplug that ?

**Comment by ffdixon** [comment]
You can certainly run it on a mobile phone, but we have a second project that is specifically targeting mobile devices.  

We shared details at the BigBlueButton World 2022 summit -- the recordings should be available shortly.  https://world.bigbluebutton.org/node/19
