### ISSUE TITLE
Demo of your screen is loading endless

### ISSUE THREAD

**Issue by dluschan** [bigbluebutton/bigbluebutton-tablet#51]
After clicking on the ‘start Broadcast’ button an inscription 'Demo of your screen is loading' with three flashing dots appeared. The BigBlueButton Broadcast did not start for 15 minutes.
* BigBlueButton Server: 2.6.0-alpha.4 (396)
* Device: iPad Pro 3 gen
* OS: iPadOS 15.7

**Comment by dluschan** [comment]
Thanks, but I'm already using the stable (2.5) version of the BigBlueButton server.

**Comment by ffdixon** [comment]
Can you visit the App store, locate "BigBlueButton Tablet", and click the Update button.

**Comment by dluschan** [comment]
Yes, I've updated client Application "BigBlueButton Tablet", but I've downgraded my BigBlueButton Server to 2.5 version without support screen share from iPad.

**Comment by TiagoJacobs** [comment]
hello @dluschan - in the demo application we have a link for a demo server (running 2.6) - does this server works properly for you?

If so, I think it's safe to close this issue.

Thank you!

**Comment by dluschan** [comment]
I had no problems with the client. The problem was with the server.
It may have been necessary to create an error report in another repository.
